name: Secure code

on:
  push:
    branches:
      - main

jobs:
  stuff:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone unsecured code
        uses: actions/checkout@v2

      - name: Clone unsecured code
        uses: actions/setup-python@v4
        with:
          python-version: "3.6.15"

      - name: Install PyArmor
        run: pip install pyarmor

      - name: Install sshpath
        run: sudo apt-get install sshpass

      - name: Securing code
        run: pyarmor obfuscate --output TGBot main.py

      - name: Send secured code with SFTP to PetrSU server
        run: sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -r ./TGBot/ posti@kappa.cs.petrsu.ru:/home/02/posti/repo2/
