name: Secure code

on:
  push:
    branches:
      - main

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Clone unsecured code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PyArmor
        run: pip install pyarmor

      - name: Securing code
        run: pyarmor obfuscate --output TGBot main.py

      - name: Send secured code with SFTP to PetrSU server
        run: |
          sftp -o StrictHostKeyChecking=no posti@kappa.cs.petrsu.ru
          ${{ secrets.PASSWORD }}
          cd repo2
          put -P ./TGBot
