name: Secure code

on:
  push:
    branches:
      - main
      - Test-Actions

jobs:
  stuff:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone unsecured code
        uses: actions/checkout@v2

      - name: Install Python 3.6.15
        uses: actions/setup-python@v4
        with:
          python-version: "3.6.15"

      - name: Install PyArmor
        run: pip install pyarmor

      - name: Install SshPass
        run: sudo apt-get install sshpass

      - name: Securing code
        run: pyarmor obfuscate --output TGBot main.py

      - name: Send secured code with SFTP to PetrSU server
        run: sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -r ./TGBot/ posti@kappa.cs.petrsu.ru:/home/02/posti/repo2/

      - name: Close screen with sessionBot name
        continue-on-error: true
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -t posti@kappa.cs.petrsu.ru
          screen -X -S sessionBot quit

      - name: Restart bot on PetrSU server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -t posti@kappa.cs.petrsu.ru
          screen -S sessionBot
          cd repo2/TGBot/
          python3 main.py
